// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0uGpQv4WTSFEgu8ejX5FMy9_jNiySS8',
    appId: '1:482713768862:web:003ecfb1571ce300bffc8f',
    messagingSenderId: '482713768862',
    projectId: 'orgfamily-c40ae',
    authDomain: 'orgfamily-c40ae.firebaseapp.com',
    storageBucket: 'orgfamily-c40ae.firebasestorage.app',
    measurementId: 'G-1QMMKSNTER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5mStFdi9q9U3XLyF2PDsiLH3V3JGhKg',
    appId: '1:482713768862:android:e8768c208d56baa6bffc8f',
    messagingSenderId: '482713768862',
    projectId: 'orgfamily-c40ae',
    storageBucket: 'orgfamily-c40ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq8B9uyjRYVHBmWTkiU77WfhUInByLYx4',
    appId: '1:482713768862:ios:fff9c42cb428f20ebffc8f',
    messagingSenderId: '482713768862',
    projectId: 'orgfamily-c40ae',
    storageBucket: 'orgfamily-c40ae.firebasestorage.app',
    androidClientId: '482713768862-4b7147bs1ddpdklaqhdnr2nmp0ajbla7.apps.googleusercontent.com',
    iosClientId: '482713768862-8o4pilg6lgkgal0to95ss0kkphj38mq9.apps.googleusercontent.com',
    iosBundleId: 'com.orgfamily.app',
  );

}